# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-02 11:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Delivered', 'Delivered'), ('Pending', 'Pending'), ('En Route', 'En Route')], max_length=256)),
            ],
            options={
                'verbose_name': 'Delivery',
                'verbose_name_plural': 'Deliveries',
            },
        ),
        migrations.AddField(
            model_name='location',
            name='address',
            field=models.CharField(default='', max_length=256, verbose_name='Address'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Location'),
        ),
        migrations.AlterField(
            model_name='order',
            name='extra_details',
            field=models.TextField(blank=True, verbose_name='extra details'),
        ),
        migrations.AlterField(
            model_name='order',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location_of_order', to='app.Location', verbose_name='Location of order'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='products',
            field=models.ManyToManyField(blank=True, to='app.Product'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Location'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='orders',
            field=models.ManyToManyField(to='app.Order'),
        ),
    ]
