# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-02 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20170502_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='warehouse',
            field=models.ManyToManyField(to='app.Warehouse', verbose_name='Pick up from'),
        ),
    ]
