# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-02 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_item_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Price'),
            preserve_default=False,
        ),
    ]
